### ISSUE TITLE
Unable to Install the Plugin in Slack, seeing bad content error.

### ISSUE THREAD

**Issue by arunics** [demisto/alfred#61]
Upon clicking "Add to Slack" button in "https://dbot.demisto.com and authorizing to install, seeing "bad content" error.
`
{
  "errors": [
    {
      "id": "bad_content",
      "status": 400,
      "title": "Bad content",
      "detail": "Request contains bad content"
    }
  ]
}  
`

Seeing the same error in 3 different workspaces.

**Comment by slavikm** [comment]
@arunics checking - looks like an expired certificate on the DB

**Comment by slavikm** [comment]
Fixed

**Comment by arunics** [comment]
Thanks
